# Generated by Django 3.1.6 on 2021-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="data",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="entry",
            name="vin",
            field=models.CharField(max_length=17),
        ),
    ]
